### ISSUE TITLE
Composer install could not find package

### ISSUE THREAD

**Issue by gcanivet** [IndicoDataSolutions/IndicoIo-PHP#70]
When running composer install, the following occurs:

Could not find package indicoio/indicoio-php at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability      

I'm unfortunately not that familiar with composer to know why this error occurs, but posting for others benefits.

**Comment by sihrc** [comment]
Sorry about that. We've only now discovered our README was slightly wrong. It has not been updated to install properly from Github.
