### ISSUE TITLE
Providing the API Key via a url parameter is going to be deprecated on July 1, 2016

### ISSUE THREAD

**Issue by sakalauskas** [IndicoDataSolutions/IndicoIo-PHP#71]
Hello,

Since last week I am getting this error, however, there is no update for this library.  As for example in Laravel, trigger_error() are being converted to Exceptions and those are being thrown. Since we are logging all the errors, there is no way to overcome the exception and handle it normally.

Providing the API Key via a url parameter is going to be deprecated on July 1, 2016. Please provide the API Key as part of a X-ApiKey header. If you are using our client library, please upgrade the client library to its latest version.

Please update the library, so we could use it.

Thanks.

**Comment by madisonmay** [comment]
Hi there!  Super sorry for the trouble, we didn't expect the addition of the warning to raise an error for folks. We'll be pushing a client lib update with those changes over the next few hours -- I'll drop you a line on this ticket when it's up on composer.

Thanks again for the report,

Madison

**Comment by sakalauskas** [comment]
Thanks for a fix!
